version: '3.9'

services:
  sender:
    build: sender
    environment:
      DEBUG: 0
      ROOT_PATH: /api
      MAIL_USERNAME: ${MAIL_USERNAME?}
      MAIL_PASSWORD: ${MAIL_PASSWORD?}
      MAIL_FROM: ${MAIL_FROM?}
      MAIL_PORT: ${MAIL_PORT?}
      MAIL_SERVER: ${MAIL_SERVER?}
      MAIL_TLS: ${MAIL_TLS?}
      MAIL_SSL: ${MAIL_SSL?}
      USE_CREDENTIALS: ${USE_CREDENTIALS?}
      VALIDATE_CERTS: ${VALIDATE_CERTS?}
  client:
    build:
      context: client
      args:
        PRODUCTION: true
        API_URL: /api
  proxy:
    build: proxy
    ports:
      - ${PROXY_PORT?}:80
